spring:
  application:
    name: JobHorizon
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

jobhorizon:
  jwt:
    secret: ${JWT_SECRET}
    expiration-hours: 24
  resend:
    api-key: ${RESEND_API_KEY}
    from-email: ${RESEND_FROM:noreply@jobhorizon.com}
  cors:
    allowed-origins: ${CORS_ORIGINS}
  frontend:
    base-url: ${FRONTEND_URL}
  r2:
    access-key: ${R2_ACCESS_KEY:dummy-access-key}
    secret-key: ${R2_SECRET_KEY:dummy-secret-key}
    account-id: ${R2_ACCOUNT_ID:dummy-account-id}
    bucket-name: ${R2_BUCKET_NAME:dummy-bucket-name}
    public-url: ${R2_PUBLIC_URL:https://pub-dummy.r2.dev}

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs