-- Migration: V12__soft_delete_catalogos.sql
ALTER TABLE Departamento ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE Distrito ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE EstadoUsuario ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE EstadoOferta ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE EstadoAplicacion ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE Genero ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE TipoDocumento ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE TipoContrato ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE NivelEducativo ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE Modalidad ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE CategoriaHabilidad ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE Habilidad ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE Idioma ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE NivelIdioma ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE NivelHabilidad ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE TipoCertificacion ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE TipoRecomendacion ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE Pais ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE TipoParticipacion ADD Activo BIT NOT NULL DEFAULT 1;
GO
ALTER TABLE TipoRedSocial ADD Activo BIT NOT NULL DEFAULT 1;
GO
